#
# API Documentation
# Howdy! Looks like you've found our open API documentation! Take a gander, and while you're at it feel free to take some endpoints for a spin.
# Version: 1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Meta
No description available.
.PARAMETER Clients
No description available.
.OUTPUTS

GetClientsResponseDto<PSCustomObject>
#>

function Initialize-PSGetClientsResponseDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Meta},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Clients}
    )

    Process {
        'Creating PSCustomObject: PSGradient => PSGetClientsResponseDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Meta) {
            throw "invalid value for 'Meta', 'Meta' cannot be null."
        }

        if ($null -eq $Clients) {
            throw "invalid value for 'Clients', 'Clients' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "meta" = ${Meta}
            "clients" = ${Clients}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to GetClientsResponseDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to GetClientsResponseDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

GetClientsResponseDto<PSCustomObject>
#>
function ConvertFrom-PSJsonToGetClientsResponseDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSGradient => PSGetClientsResponseDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PSGetClientsResponseDto
        $AllProperties = ("meta", "clients")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'meta' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "meta"))) {
            throw "Error! JSON cannot be serialized due to the required property 'meta' missing."
        } else {
            $Meta = $JsonParameters.PSobject.Properties["meta"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "clients"))) {
            throw "Error! JSON cannot be serialized due to the required property 'clients' missing."
        } else {
            $Clients = $JsonParameters.PSobject.Properties["clients"].value
        }

        $PSO = [PSCustomObject]@{
            "meta" = ${Meta}
            "clients" = ${Clients}
        }

        return $PSO
    }

}

