#
# API Documentation
# Howdy! Looks like you've found our open API documentation! Take a gander, and while you're at it feel free to take some endpoints for a spin.
# Version: 1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum ServiceSubCategoryEnum.

.DESCRIPTION

No description available.
#>

enum ServiceSubCategoryEnum {
    # enum value: "endpoint detection and response (EDR)"
    endpoint_detection_and_response__EDR
    # enum value: "email security"
    email_security
    # enum value: "virtual private network services (VPN)"
    virtual_private_network_services__VPN
    # enum value: "DNS filtering"
    DNS_filtering
    # enum value: "dark web monitoring"
    dark_web_monitoring
    # enum value: "password management"
    password_management
    # enum value: "single sign on (SSO)"
    single_sign_on__SSO
    # enum value: "priviledged access and identity management (PAM/PIM)"
    priviledged_access_and_identity_management__PAM_PIM
    # enum value: "security information and event management (SIEM)"
    security_information_and_event_management__SIEM
    # enum value: "mobile device management (MDM)"
    mobile_device_management__MDM
    # enum value: "application security"
    application_security
    # enum value: "mobile application management (MAM)"
    mobile_application_management__MAM
    # enum value: "multi factor authentication (MFA)"
    multi_factor_authentication__MFA
    # enum value: "cloud backup"
    cloud_backup
    # enum value: "local backup"
    local_backup
    # enum value: "desktop backup"
    desktop_backup
    # enum value: "data archiving"
    data_archiving
    # enum value: "physical offsite storage"
    physical_offsite_storage
    # enum value: "business continuity"
    business_continuity
    # enum value: "hosted email"
    hosted_email
    # enum value: "video conferencing"
    video_conferencing
    # enum value: "voice over IP services (VOIP)"
    voice_over_IP_services__VOIP
    # enum value: "line of business application support"
    line_of_business_application_support
    # enum value: "unified communications as a service (UCaaS)"
    unified_communications_as_a_service__UCaaS
    # enum value: "customer relationship management"
    customer_relationship_management
    # enum value: "cloud storage"
    cloud_storage
    # enum value: "website hosting"
    website_hosting
    # enum value: "hardware as a service (HaaS)"
    hardware_as_a_service__HaaS
    # enum value: "managed print services"
    managed_print_services
    # enum value: "virtual desktop infrastructure (VDI)"
    virtual_desktop_infrastructure__VDI
    # enum value: "virtual server hosting"
    virtual_server_hosting
    # enum value: "infrastructure as a service (IaaS)"
    infrastructure_as_a_service__IaaS
    # enum value: "end user support"
    end_user_support
    # enum value: "server management and support"
    server_management_and_support
    # enum value: "network management and support"
    network_management_and_support
    # enum value: "printer management and support"
    printer_management_and_support
    # enum value: "desktop management and support"
    desktop_management_and_support
    # enum value: "hosted security operations centre (SOC)"
    hosted_security_operations_centre__SOC
    # enum value: "software development"
    software_development
    # enum value: "penetration testing"
    penetration_testing
    # enum value: "project services"
    project_services
    # enum value: "governance and compliance"
    governance_and_compliance
    # enum value: "business intelligence services / analytics"
    business_intelligence_services___analytics
    # enum value: "phishing simulation"
    phishing_simulation
    # enum value: "privacy and security awareness training"
    privacy_and_security_awareness_training
    # enum value: "other"
    other
}

