#
# API Documentation
# Howdy! Looks like you've found our open API documentation! Take a gander, and while you're at it feel free to take some endpoints for a spin.
# Version: 1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum ServiceCategoryEnum.

.DESCRIPTION

No description available.
#>

enum ServiceCategoryEnum {
    # enum value: "security"
    security
    # enum value: "backup"
    backup
    # enum value: "productivity"
    productivity
    # enum value: "infrastructure"
    infrastructure
    # enum value: "service delivery"
    service_delivery
    # enum value: "consulting"
    consulting
    # enum value: "other"
    other
}

