#
# API Documentation
# Howdy! Looks like you've found our open API documentation! Take a gander, and while you're at it feel free to take some endpoints for a spin.
# Version: 1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum VendorIntegrationStatusEnum.

.DESCRIPTION

No description available.
#>

enum VendorIntegrationStatusEnum {
    # enum value: "active"
    active
    # enum value: "inactive"
    inactive
    # enum value: "pending"
    pending
    # enum value: "disabled"
    disabled
    # enum value: "error"
    error
}

