#
# API Documentation
# Howdy! Looks like you've found our open API documentation! Take a gander, and while you're at it feel free to take some endpoints for a spin.
# Version: 1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Status
No description available.
.PARAMETER ExternalIntegrationStatus
No description available.
.PARAMETER Variation
No description available.
.OUTPUTS

VendorIntegrationData<PSCustomObject>
#>

function Initialize-PSVendorIntegrationData {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("active", "inactive", "pending")]
        [PSCustomObject]
        ${Status},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("active", "inactive", "pending")]
        [PSCustomObject]
        ${ExternalIntegrationStatus},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("alerts", "billing")]
        [PSCustomObject]
        ${Variation}
    )

    Process {
        'Creating PSCustomObject: PSGradient => PSVendorIntegrationData' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Status) {
            throw "invalid value for 'Status', 'Status' cannot be null."
        }

        if ($null -eq $ExternalIntegrationStatus) {
            throw "invalid value for 'ExternalIntegrationStatus', 'ExternalIntegrationStatus' cannot be null."
        }

        if ($null -eq $Variation) {
            throw "invalid value for 'Variation', 'Variation' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "status" = ${Status}
            "externalIntegrationStatus" = ${ExternalIntegrationStatus}
            "variation" = ${Variation}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VendorIntegrationData<PSCustomObject>

.DESCRIPTION

Convert from JSON to VendorIntegrationData<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VendorIntegrationData<PSCustomObject>
#>
function ConvertFrom-PSJsonToVendorIntegrationData {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSGradient => PSVendorIntegrationData' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PSVendorIntegrationData
        $AllProperties = ("status", "externalIntegrationStatus", "variation")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'status' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "status"))) {
            throw "Error! JSON cannot be serialized due to the required property 'status' missing."
        } else {
            $Status = $JsonParameters.PSobject.Properties["status"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "externalIntegrationStatus"))) {
            throw "Error! JSON cannot be serialized due to the required property 'externalIntegrationStatus' missing."
        } else {
            $ExternalIntegrationStatus = $JsonParameters.PSobject.Properties["externalIntegrationStatus"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "variation"))) {
            throw "Error! JSON cannot be serialized due to the required property 'variation' missing."
        } else {
            $Variation = $JsonParameters.PSobject.Properties["variation"].value
        }

        $PSO = [PSCustomObject]@{
            "status" = ${Status}
            "externalIntegrationStatus" = ${ExternalIntegrationStatus}
            "variation" = ${Variation}
        }

        return $PSO
    }

}

