#
# API Documentation
# Howdy! Looks like you've found our open API documentation! Take a gander, and while you're at it feel free to take some endpoints for a spin.
# Version: 1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum VendorModuleVariationEnum.

.DESCRIPTION

No description available.
#>

enum VendorModuleVariationEnum {
    # enum value: "alerts"
    alerts
    # enum value: "billing"
    billing
}

